/**
 * Vietnamese finance sentiment keywords.
 * Includes both có dấu and không dấu, plus English finance terms.
 */

export const POSITIVE_KEYWORDS = [
  "acceleration", "accretive", "ăn trọn sóng", "an tron song", "all-time high",
  "alpha", "appreciating", "ath", "beat estimates", "beat expectations",
  "bền vững", "ben vung", "best performer", "best quarter", "bứt phá", "but pha",
  "bùng nổ", "bung no", "blue chip", "boom", "booming", "boost", "bottom fishing",
  "bounce", "bouncing", "breakout", "breakthrough", "bright outlook", "bull market",
  "bull run", "bullish", "buy signal", "buyback",
  "cải thiện", "cai thien", "cao điểm", "cao diem", "cao kỷ lục", "cao ky luc",
  "cao nhất", "cao nhat", "cao nhất lịch sử", "cao nhat lich su",
  "cổ phiếu blue chip", "co phieu blue chip", "cổ phiếu hot", "co phieu hot",
  "cổ phiếu ngon", "co phieu ngon", "cổ phiếu tiềm năng", "co phieu tiem nang",
  "cổ phiếu tốt", "co phieu tot", "cổ tức cao", "co tuc cao",
  "cổ tức hấp dẫn", "co tuc hap dan", "cổ tức khủng", "co tuc khung",
  "capital inflow", "chạm đỉnh", "cham dinh", "chinh phục", "chinh phuc",
  "chốt lãi", "chot lai", "chốt lời", "chot loi",
  "cơ hội đầu tư", "co hoi dau tu", "cơ hội mua", "co hoi mua",
  "cơ hội vàng", "co hoi vang",
  "dẫn dắt", "dan dat", "dẫn đầu", "dan dau",
  "dấu hiệu phục hồi", "dau hieu phuc hoi",
  "dấu hiệu tăng trưởng", "dau hieu tang truong",
  "dấu hiệu tích cực", "dau hieu tich cuc",
  "dòng tiền mạnh", "dong tien manh", "dòng tiền vào", "dong tien vao",
  "dư địa tăng trưởng", "du dia tang truong",
  "dự báo tích cực", "du bao tich cuc",
  "đà phục hồi", "da phuc hoi", "đà tăng", "da tang",
  "đà tăng trưởng", "da tang truong",
  "đáng mua", "dang mua", "đáng đầu tư", "dang dau tu",
  "đầu tư giá trị", "dau tu gia tri", "đầu tư thông minh", "dau tu thong minh",
  "đột phá", "dot pha", "đẩy mạnh", "day manh",
  "deep value", "demand strong", "diamond hands", "dip buying",
  "dividend growth", "dividend increase", "dividend yield", "double digit growth",
  "ebitda growth", "eps beat", "eps growth", "exceed expectations",
  "excellent", "exceptional", "expansion", "exponential", "favorable",
  "fdi inflow", "foreign inflow",
  "gaining", "gaining momentum", "gains", "gdp growth",
  "giá hấp dẫn", "gia hap dan", "giá hợp lý", "gia hop ly",
  "giá tốt", "gia tot", "giá trần", "gia tran",
  "giảm lãi suất", "giam lai suat", "gom hàng", "gom hang",
  "golden cross", "good buy", "good news", "good performance", "good quarter",
  "green", "green day", "green shoots", "gross margin expansion",
  "growing", "growth", "growth momentum", "growth stock", "guidance raise",
  "healthy", "healthy growth", "high conviction", "high demand", "high dividend",
  "high growth", "high margin", "high potential", "high quality", "high volume",
  "higher high", "highest", "hit target", "hold strong", "hot stock",
  "hưng phấn", "hung phan",
  "improved", "improvement", "impressive", "increasing", "inflow",
  "innovation", "insider buying", "institutional buying", "interest rate cut",
  "investment grade", "investor confidence", "ipo success",
  "jump", "jumping",
  "khả quan", "kha quan", "khối lượng cao", "khoi luong cao",
  "khối lượng đột biến", "khoi luong dot bien",
  "khối lượng khủng", "khoi luong khung",
  "khối ngoại mua", "khoi ngoai mua",
  "khả năng sinh lời", "kha nang sinh loi",
  "kỳ vọng tăng trưởng", "ky vong tang truong", "kỷ lục", "ky luc",
  "lạc quan", "lac quan", "lãi cao", "lai cao", "lãi khủng", "lai khung",
  "lãi lớn", "lai lon", "lãi ròng tăng", "lai rong tang",
  "lãi suất giảm", "lai suat giam",
  "leader", "leadership", "leading",
  "lên giá", "len gia", "lên sóng", "len song", "lên đỉnh", "len dinh",
  "lọt rổ etf", "lot ro etf", "lọt top", "lot top",
  "lợi nhuận cao", "loi nhuan cao", "lợi nhuận khủng", "loi nhuan khung",
  "lợi nhuận tăng", "loi nhuan tang", "lợi nhuận tốt", "loi nhuan tot",
  "lực mua mạnh", "luc mua manh", "lực mua", "luc mua",
  "margin expansion", "market leader", "market share gain",
  "mạnh", "manh", "mạnh mẽ", "manh me", "mở rộng", "mo rong",
  "mua đáy", "mua day", "mua mạnh", "mua manh",
  "mua ròng", "mua rong", "mua vào", "mua vao",
  "milestone", "momentum", "multibagger",
  "nền tảng vững", "nen tang vung", "nhu cầu cao", "nhu cau cao",
  "nổi bật", "noi bat",
  "net profit rise", "new contract", "new high", "new order",
  "new partnership", "new record",
  "optimism", "optimistic", "outperform", "outperformance", "overweight",
  "peak", "phá đỉnh", "pha dinh", "phá kháng cự", "pha khang cu",
  "phá mốc", "pha moc", "phấn khởi", "phan khoi",
  "phục hồi", "phuc hoi", "phục hồi mạnh", "phuc hoi manh",
  "positive", "positive outlook", "positive sentiment", "positive surprise",
  "potential", "price target raised", "price target upgrade",
  "profit beat", "profit growth", "profit surge", "profitable", "promising",
  "quý tốt", "quy tot", "quality stock",
  "rally", "rallying", "rating upgrade", "rebound", "rebounding",
  "record", "record breaking", "record high", "record profit", "record revenue",
  "recovery", "resilient", "revenue beat", "revenue growth", "revenue surge",
  "rising", "rising star", "roe high",
  "rủi ro thấp", "rui ro thap", "sắc xanh", "sac xanh",
  "safe haven", "sector leader",
  "siêu cổ phiếu", "sieu co phieu", "sinh lời", "sinh loi",
  "skyrocket", "soaring", "solid", "solid growth",
  "sóng lớn", "song lon", "spike", "stable", "stellar", "stimulus",
  "strategic", "strategic investment", "strength", "strengthen",
  "strong", "strong buy", "strong cash flow", "strong demand",
  "strong earnings", "strong fundamentals", "strong momentum",
  "strong performance", "strong quarter", "strong volume",
  "successful", "sức mạnh", "suc manh",
  "surge", "surging", "sustainable", "sustainable growth",
  "tăng", "tang", "tăng cường", "tang cuong", "tăng giá", "tang gia",
  "tăng khối lượng", "tang khoi luong", "tăng kỷ lục", "tang ky luc",
  "tăng lãi", "tang lai", "tăng mạnh", "tang manh",
  "tăng ổn định", "tang on dinh", "tăng tốc", "tang toc",
  "tăng trần", "tang tran", "tăng trưởng", "tang truong",
  "tăng trưởng bền vững", "tang truong ben vung",
  "tăng trưởng cao", "tang truong cao",
  "tăng trưởng doanh thu", "tang truong doanh thu",
  "tăng trưởng đột biến", "tang truong dot bien",
  "tăng trưởng lợi nhuận", "tang truong loi nhuan",
  "tăng trưởng mạnh", "tang truong manh",
  "tăng trưởng tốt", "tang truong tot",
  "tăng vốn thành công", "tang von thanh cong",
  "tập trung mua", "tap trung mua",
  "target raised", "technical breakout",
  "thắng lớn", "thang lon", "thành công", "thanh cong",
  "thâu tóm thành công", "thau tom thanh cong",
  "thị trường tăng", "thi truong tang", "thị trường tốt", "thi truong tot",
  "thịnh vượng", "thinh vuong",
  "thông tin tích cực", "thong tin tich cuc",
  "thu hút đầu tư", "thu hut dau tu", "thu hút vốn", "thu hut von",
  "tiềm năng", "tiem nang", "tiềm năng lớn", "tiem nang lon",
  "tiềm năng tăng", "tiem nang tang",
  "tín hiệu mua", "tin hieu mua", "tín hiệu tích cực", "tin hieu tich cuc",
  "tích cực", "tich cuc", "tích luỹ", "tich luy",
  "tốt", "tot", "tốt hơn dự kiến", "tot hon du kien",
  "to the moon", "top gainer", "top performer", "top pick",
  "turnaround",
  "tỷ suất lợi nhuận cao", "ty suat loi nhuan cao",
  "undervalued", "unlock value", "upcycle", "upbeat",
  "upgrade", "upside", "upside potential", "uptrend", "upward", "upward momentum",
  "vnindex tăng", "vnindex tang",
  "vốn hóa tăng", "von hoa tang",
  "vững chắc", "vung chac", "vững mạnh", "vung manh",
  "vượt kỳ vọng", "vuot ky vong", "vượt mục tiêu", "vuot muc tieu",
  "vượt trội", "vuot troi",
  "winning", "win-win", "x2", "x3", "x5", "x10",
  "xanh", "year high", "yield strong"
];

export const NEGATIVE_KEYWORDS = [
  "ảm đạm", "am dam", "áp lực bán", "ap luc ban",
  "áp lực giảm", "ap luc giam", "áp lực", "ap luc",
  "accounting fraud", "accounting scandal", "adverse", "all-time low",
  "bankruptcy",
  "báo cáo xấu", "bao cao xau", "bẫy bull", "bay bull",
  "bẫy giá", "bay gia", "bán mạnh", "ban manh",
  "bán ròng", "ban rong", "bán tháo", "ban thao",
  "bắt dao rơi", "bat dao roi",
  "bị bán tháo", "bi ban thao", "bị mắc kẹt", "bi mac ket",
  "bong bóng", "bong bong",
  "bubble", "bubble burst", "bear market", "bear trap", "bearish",
  "beating down", "below expectations", "bleeding",
  "bond default", "break down", "breakdown", "breaking support",
  "burn", "burning", "bust",
  "cạn kiệt", "can kiet", "cảnh báo", "canh bao",
  "cảnh báo lỗ", "canh bao lo", "cảnh giác", "canh giac",
  "cắt lỗ", "cat lo", "cháy tài khoản", "chay tai khoan",
  "chậm trễ", "cham tre", "chạm đáy", "cham day",
  "chìm", "chim", "chìm nghỉm", "chim nghim",
  "chính sách thắt chặt", "chinh sach that chat",
  "cổ phiếu rác", "co phieu rac", "cổ phiếu xấu", "co phieu xau",
  "cổ tức cắt giảm", "co tuc cat giam", "cổ tức giảm", "co tuc giam",
  "cash burn", "cash crunch", "catastrophic", "caution", "cautious",
  "collapse", "collapsing", "concern", "contagion",
  "contract loss", "correction", "corruption",
  "crash", "crashing", "credit downgrade", "credit rating cut",
  "crisis", "critical", "crunch",
  "cut dividend", "cut forecast", "cut guidance", "cut jobs", "cut outlook",
  "dấu hiệu giảm", "dau hieu giam",
  "dấu hiệu tiêu cực", "dau hieu tieu cuc",
  "dấu hiệu xấu", "dau hieu xau",
  "dead cat bounce", "dead money", "death cross",
  "debt burden", "debt crisis", "debt default", "debt high", "debt problem",
  "decline", "declining", "declining margin", "deep loss",
  "default", "defaulting", "deficit",
  "delisting", "delisting risk", "demand weak",
  "depreciation", "deteriorate", "deteriorating", "devaluation",
  "devastating", "dilution", "disappointing", "disappointment", "disastrous",
  "dividend cut",
  "doanh thu giảm", "doanh thu giam",
  "dòng tiền ra", "dong tien ra", "dòng tiền yếu", "dong tien yeu",
  "downgrade", "downside", "downtrend", "downturn",
  "downward", "downward pressure", "downward revision", "downward spiral",
  "drop", "dropping",
  "dự báo giảm", "du bao giam", "dự báo tiêu cực", "du bao tieu cuc",
  "dự báo xấu", "du bao xau",
  "dump", "dumping",
  "đáy", "đáy mới", "day moi",
  "đỏ", "do", "đỏ lửa", "do lua", "đỏ sàn", "do san",
  "earnings miss", "earnings warning", "ebitda decline",
  "economic crisis", "economic recession", "emergency",
  "eps miss", "erode", "eroding", "erosion",
  "fail", "failed", "failing", "failure", "falling", "falling knife",
  "fear", "fined", "flop", "forced selling", "forecast cut",
  "foreign outflow", "fraud", "free fall", "frozen",
  "giá giảm", "gia giam", "giá rớt", "gia rot",
  "giá sàn", "gia san", "giá xuống", "gia xuong",
  "giảm", "giam", "giảm điểm", "giam diem",
  "giảm giá", "giam gia", "giảm khối lượng", "giam khoi luong",
  "giảm lãi", "giam lai", "giảm mạnh", "giam manh",
  "giảm sàn", "giam san", "giảm sâu", "giam sau",
  "giảm tốc", "giam toc",
  "going concern", "going down", "guidance miss",
  "halted", "halt trading", "hammered", "harsh", "headwind", "heavy loss",
  "hoảng loạn", "hoang loan", "hoảng sợ", "hoang so",
  "hurt", "hurting", "hụt hơi", "hut hoi", "hụt kỳ vọng", "hut ky vong",
  "impairment", "insolvent", "insider selling", "insolvency",
  "institutional selling", "interest rate hike", "investigation",
  "ipo flop", "ipo failed",
  "kém", "kem", "kém hiệu quả", "kem hieu qua",
  "kém khả quan", "kem kha quan",
  "kẹt", "ket", "kẹt giá", "ket gia", "kẹt hàng", "ket hang",
  "khó khăn", "kho khan",
  "khối lượng giảm", "khoi luong giam", "khối lượng yếu", "khoi luong yeu",
  "khối ngoại bán", "khoi ngoai ban",
  "khủng hoảng", "khung hoang", "khủng hoảng nợ", "khung hoang no",
  "khủng hoảng thanh khoản", "khung hoang thanh khoan",
  "kiệt quệ", "kiet que",
  "làm ăn thua lỗ", "lam an thua lo",
  "lao dốc", "lao doc",
  "lỗ", "lo", "lỗ ròng", "lo rong", "lỗ lớn", "lo lon",
  "lỗ nặng", "lo nang", "lỗ tiếp", "lo tiep",
  "lợi nhuận giảm", "loi nhuan giam",
  "lợi nhuận sụt", "loi nhuan sut", "lợi nhuận xấu", "loi nhuan xau",
  "lùi giá", "lui gia",
  "lack confidence", "lawsuit", "layoff", "leadership crisis",
  "legal issue", "leverage high", "liability", "license revoked",
  "liquidity crisis", "liquidity crunch", "liquidity weak", "litigation",
  "locked", "lose", "loser", "losing", "loss",
  "lower high", "lower low", "lowest",
  "lực bán", "luc ban", "lực bán mạnh", "luc ban manh",
  "m&a failed", "mắc kẹt", "mac ket",
  "mất điểm", "mat diem", "mất giá", "mat gia",
  "mất niềm tin", "mat niem tin", "mất vốn", "mat von",
  "margin call", "margin compression", "margin decline",
  "market cap decline", "market crash", "market panic",
  "market sell-off", "market share loss",
  "massive loss", "massive outflow", "massive sell-off",
  "merger failed", "meltdown",
  "miss", "miss earnings", "miss estimate", "miss forecast", "miss target",
  "negative", "negative earnings", "negative margin",
  "negative outlook", "negative sentiment", "negative surprise",
  "ngập nợ", "ngap no", "nghi ngờ", "nghi ngo",
  "ngừng trả cổ tức", "ngung tra co tuc",
  "nguy cơ phá sản", "nguy co pha san", "nguy hiểm", "nguy hiem",
  "nhà đầu tư bán", "nha dau tu ban",
  "nợ cao", "no cao", "nợ nần", "no nan",
  "nợ quá hạn", "no qua han", "nợ xấu", "no xau",
  "no growth", "non-performing loan", "nosedive",
  "operating loss", "outflow", "overpriced", "overvalued",
  "panic", "panic selling", "paper loss", "penalty", "penny stock",
  "phá sản", "pha san", "phá vỡ hỗ trợ", "pha vo ho tro",
  "phạt", "phat",
  "plummet", "plummeting", "plunge", "plunging",
  "ponzi", "poor", "poor earnings", "poor performance",
  "poor quarter", "poor result", "pressure", "problem",
  "profit decline", "profit margin down", "profit warning", "pump and dump",
  "quá giá", "qua gia", "quá đắt", "qua dat",
  "rác", "rac", "rating cut", "rating downgrade",
  "recession", "record loss", "red", "red day", "red flag",
  "regulation tighten", "resistance strong", "restatement",
  "restructure failed", "result miss",
  "revenue decline", "revenue drop", "revenue miss",
  "risk", "risk high", "risky", "roe decline",
  "rủi ro cao", "rui ro cao", "rủi ro lớn", "rui ro lon",
  "sanction", "sắc đỏ", "sac do", "sập", "sap",
  "scandal", "sector decline", "sell signal", "sell-off", "selling pressure",
  "shares crash", "shares plunge", "shortage",
  "shrink", "shrinking", "shut down", "sink", "sinking",
  "slide", "sliding", "slowing", "slowdown", "slump", "slumping",
  "sốc", "soc", "sợ hãi", "so hai",
  "spiral down", "stagnant", "stagnation",
  "stock dilution", "stop loss", "struggling", "stuck", "stumble",
  "substantial loss",
  "sụp đổ", "sup do", "sụt giảm", "sut giam",
  "suy giảm", "suy giam", "suy thoái", "suy thoai",
  "suy yếu", "suy yeu",
  "suspended", "suspension",
  "tài sản giảm", "tai san giam", "tệ", "te",
  "terrible", "thâm hụt", "tham hut", "thảm họa", "tham hoa",
  "thất bại", "that bai",
  "thị trường giảm", "thi truong giam", "thị trường xấu", "thi truong xau",
  "thiệt hại", "thiet hai",
  "thông tin tiêu cực", "thong tin tieu cuc",
  "thông tin xấu", "thong tin xau",
  "thu hẹp", "thu hep", "thu hồi giấy phép", "thu hoi giay phep",
  "thua lỗ", "thua lo", "thua lỗ nặng", "thua lo nang",
  "tiêu cực", "tieu cuc",
  "tín hiệu bán", "tin hieu ban",
  "tín hiệu tiêu cực", "tin hieu tieu cuc",
  "tồi", "toi", "tồi tệ", "toi te",
  "toxic", "trading halt", "trap", "trapped", "troubled",
  "tumble", "tumbling", "turmoil",
  "uncertainty", "underperform", "underweight",
  "unemployment rise", "unfavorable", "unprofitable",
  "unstable", "unsustainable",
  "vỡ nợ", "vo no", "violation",
  "vnindex giảm", "vnindex giam",
  "volatile", "volatility high", "volume weak", "vulnerable",
  "warning", "weak", "weak demand", "weak earnings",
  "weak fundamentals", "weak performance", "weak quarter",
  "weaken", "weakening", "weakness",
  "wipe out", "worst", "worst performer", "worst quarter", "worthless",
  "write-down", "write-off",
  "xấu", "xau", "xấu đi", "xau di",
  "xấu hơn dự kiến", "xau hon du kien",
  "xuống", "xuong", "xuống giá", "xuong gia", "xuống sâu", "xuong sau",
  "year low", "yếu", "yeu", "yếu kém", "yeu kem", "yếu thế", "yeu the"
];

/**
 * Analyze sentiment of a Vietnamese finance headline.
 * Checks title + summary against keyword lists.
 * @param {string} title
 * @param {string} [summary]
 * @returns {"positive" | "negative" | "neutral"}
 */
export function analyzeSentiment(title, summary = "") {
  const text = (title + " " + summary).toLowerCase();

  let posScore = 0;
  let negScore = 0;

  for (const kw of POSITIVE_KEYWORDS) {
    if (text.includes(kw)) posScore++;
  }
  for (const kw of NEGATIVE_KEYWORDS) {
    if (text.includes(kw)) negScore++;
  }

  if (posScore > negScore) return "positive";
  if (negScore > posScore) return "negative";
  return "neutral";
}
